"""add powens connection

Revision ID: 09649c6b1a49
Revises: 50390d0d06a1
Create Date: 2025-12-29 14:04:29.327146

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09649c6b1a49"
down_revision: Union[str, Sequence[str], None] = "50390d0d06a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("powensconnection")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "powensconnection",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "powens_access_token", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "powens_connection_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("powensconnection_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("powensconnection_pkey")),
    )
    # ### end Alembic commands ###
