"""Add internal transactions

Revision ID: 9cb5d4e2cd5b
Revises: 988d985ab54f
Create Date: 2025-12-30 22:59:26.335251

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cb5d4e2cd5b"
down_revision: Union[str, Sequence[str], None] = "988d985ab54f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "is_internal", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "transactions", sa.Column("internal_link_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "transactions", "transactions", ["internal_link_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_column("transactions", "internal_link_id")
    op.drop_column("transactions", "is_internal")
    # ### end Alembic commands ###
