"""add accounts

Revision ID: a7df5f188a54
Revises: 09649c6b1a49
Create Date: 2025-12-29 18:31:44.688146

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7df5f188a54"
down_revision: Union[str, Sequence[str], None] = "09649c6b1a49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_income", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("transactions", sa.Column("account_id", sa.Uuid(), nullable=False))
    op.add_column("transactions", sa.Column("category_id", sa.Uuid(), nullable=True))
    op.add_column(
        "transactions",
        sa.Column(
            "powens_transaction_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "transactions",
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("transactions", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.create_index(
        op.f("ix_transactions_powens_transaction_id"),
        "transactions",
        ["powens_transaction_id"],
        unique=True,
    )
    op.create_foreign_key(None, "transactions", "accounts", ["account_id"], ["id"])
    op.create_foreign_key(None, "transactions", "categories", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_index(
        op.f("ix_transactions_powens_transaction_id"), table_name="transactions"
    )
    op.drop_column("transactions", "is_deleted")
    op.drop_column("transactions", "raw_data")
    op.drop_column("transactions", "powens_transaction_id")
    op.drop_column("transactions", "category_id")
    op.drop_column("transactions", "account_id")
    op.drop_table("categories")
    # ### end Alembic commands ###
