"""update powens token

Revision ID: f5d4a5aac38b
Revises: a7df5f188a54
Create Date: 2025-12-29 22:38:45.945362

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5d4a5aac38b"
down_revision: Union[str, Sequence[str], None] = "a7df5f188a54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("powensconnection", "powens_connection_id")
    op.alter_column(
        "transactions", "account_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_column("transactions", "is_virtual")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("is_virtual", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "transactions", "account_id", existing_type=sa.UUID(), nullable=False
    )
    op.add_column(
        "powensconnection",
        sa.Column(
            "powens_connection_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
