name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  call-deploy:
    uses: buddies-company/actions/.github/workflows/deploy.yml@main
    with:
      front_path: "savibud-front"
      api_path: "savibud-api"
    secrets:
      FRONT_ENV_FILE: ${{ secrets.FRONT_ENV_FILE }}
      API_ENV_FILE: ${{ secrets.API_ENV_FILE }}
      GH_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}